### PR TITLE
Free dev from compojure

### PR DESCRIPTION
**Pull request by cch1**
This is a resubmission of @bonkydog's PR #175.  It retains the use of `case` in preference to `condp =` (which in this case is preferable -see my comment in commit) and addresses issues #103 and #270.  And, as requested in #175, it has been rebased onto master.

### CODE REVIEW

**Comment by ordnungswidrig** [comment]
Great work! Would you mind to squash the commits a little. There's a lot of back and forth in the log :-)

**Comment by cch1** [comment]
Sure.  I was trying to preserve @bonkydog 's commits since he deserves some credit.  But I guess this thread will suffice.

**Comment by cch1** [comment]
Done.

**Comment by bonkydog** [comment]
@cch1 Aw, thanks, but don't worry about it.  Sorry I haven't been able to contribute recently.

**Comment by ordnungswidrig** [comment]
I'll try to remember his contribution in the changelog!

**Pull request merged**
