### PR TITLE
Parse entity in processable? and add valid-entity? for validation

### PR DESCRIPTION
**Pull request by ordnungswidrig**
The support for parsing of request entitiy is experimental, incomplete
and not documented.

### CODE REVIEW

**Comment by cch1** [comment]
Did anything else attempt to request this need?  It seems appropriate for liberator to handle this task as it is quite symmetric with the response processing.

**Comment by ordnungswidrig** [comment]
There's support for `parse-request-entity`, see https://github.com/clojure-liberator/liberator/blob/a933a62e5b8d477ba1149b8e51362186c4dc9212/test/test_representation.clj#L90

I think the docs need be updated on that, actually.

**Comment by ordnungswidrig** [comment]
I plan to to a release this week which will include this.

**Comment by cch1** [comment]
Awesome!

**Pull request closed without merging**
