### PR TITLE
Add JDK 11 and JDK-ea to test matrix

### PR DESCRIPTION
**Pull request by danielcompton**

### CODE REVIEW

**Comment by ordnungswidrig** [comment]
Thanks for the contribution, as it seams there's some problems with jdk 11 and the examples.

**Comment by danielcompton** [comment]
Yep, I think it's the ClojureScript dependency that's causing the problem. I'm not sure what combinations of old versions of Clojure and new versions of ClojureScript that work with Java 11 are valid. If you wanted to keep testing against old versions of Clojure then you could probably do something clever with the Travis build matrix feature.

**Comment by ordnungswidrig** [comment]
The project descriptor and build matrix was cleaned up in #303. I think this PR can be closed. @danielcompton thoughts?

**Comment by ordnungswidrig** [comment]
@danielcompton Thanks for the contribution!

**Pull request closed without merging**
