### PR TITLE
Remove javax.xml.ws dependency

### PR DESCRIPTION
**Pull request by brogowski**
Fix for #290

### CODE REVIEW

**Comment by ordnungswidrig** [comment]
Can you add a one-liner to `CHANGES.markdown` add a section on top for `unreleased` above 0.15.1

**Comment by brogowski** [comment]
Sure, I didn't notice that v0.15.1 was already released.

**Comment by ordnungswidrig** [comment]
Thanks for the PR. I will add some more tests in travis to ensure 1.9 compatibility and release as soon as I can.

**Comment by ordnungswidrig** [comment]
Famous last words... 😌 Planning release for this week.

**Pull request merged**
