### PR TITLE
Fix 107 post conflict

### PR DESCRIPTION
**Pull request by jimmythompson**
This is a rebase of #246, so it can be merged. It includes an updated trace.svg. 😄 

We made this change after consulting with @duncanmortimer and @tobyclemson.

We will make a separate PR for the changes to Github Pages.

### CODE REVIEW

**Comment by ordnungswidrig** [comment]
Hurray! Thanks for the patch!

**Comment by jimmythompson** [comment]
Awesome, thanks for the quick response! Any idea on timeline for release?

Thanks

**Comment by ordnungswidrig** [comment]
I plan to release until this Friday.

**Comment by tobyclemson** [comment]
@ordnungswidrig anything we can do help with getting a release out? We are currently waiting on this.

Thanks

**Comment by ordnungswidrig** [comment]
I want to merge #282 and release after that. Sorry for the delay.

**Pull request merged**
